/* __folly_char_traits_fix__ */
// Auto-generated by the backend build pipeline. Do not edit by hand — it is
// re-applied idempotently on every iOS IPA build. Safe to delete: at worst
// the Xcode 16.3/iOS 18.4 RCT-Folly char_traits<unsigned char> build error
// returns.
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '__folly_char_traits_fix__';

// CocoaPods only permits one post_install block, and Expo's RN template
// already ships one — so this snippet is spliced right after that block's
// `|installer|` line instead of being registered as a second top-level
// post_install block.
const SNIPPET = `
  # \${MARKER}
  # Written OUTSIDE installer.sandbox.root (the Pods/ directory) on purpose.
  # A prior version wrote this under Pods/Headers/Private/_FollyCharTraitsFix
  # — CocoaPods' own sandbox finalization step prunes files under
  # Pods/Headers/Public and Pods/Headers/Private that aren't part of any
  # pod's declared header list, so our injected file was being deleted
  # AFTER this post_install hook wrote it but BEFORE the archive step read
  # it (confirmed via a real CI failure: "file not found" for a file this
  # hook demonstrably creates, no matter what HEADER_SEARCH_PATHS said).
  # Placing it as a sibling of Pods/ instead keeps it outside anything
  # CocoaPods manages or cleans.
  folly_shim_dir = File.expand_path(File.join(installer.sandbox.root, '..', '_FollyCharTraitsFix'))
  FileUtils.mkdir_p(folly_shim_dir)
  folly_shim_header = File.join(folly_shim_dir, 'folly_char_traits_fix.h')
  File.write(folly_shim_header, <<~FOLLY_HEADER)
    #ifndef FOLLY_CHAR_TRAITS_FIX_H
    #define FOLLY_CHAR_TRAITS_FIX_H
    #include <string>
    namespace std {
      template<> struct char_traits<unsigned char> : public char_traits<char> {
        using char_type = unsigned char;
      };
    }
    #endif
  FOLLY_HEADER

  # Applied to every Pods target, not just RCT-Folly: this is a genuine gap
  # in Xcode 16.3's libc++ (no std::char_traits<unsigned char> specialization
  # anywhere in the SDK), so any target that transitively includes
  # <string>/<string_view> with unsigned char can hit it — confirmed via a
  # real CI failure where React-jsinspector (RuntimeAgent.cpp,
  # RuntimeTarget.cpp) hit this exact error after RCT-Folly alone was fixed.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |cfg|
      flags = cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
      flags = [flags] unless flags.is_a?(Array)
      cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags + ['-include', folly_shim_header]

      search_paths = cfg.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
      search_paths = [search_paths] unless search_paths.is_a?(Array)
      cfg.build_settings['HEADER_SEARCH_PATHS'] = search_paths + [folly_shim_dir]
    end
  end
`;

function withFollyCharTraitsFix(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfilePath)) return config;

      let contents = fs.readFileSync(podfilePath, 'utf8');
      if (contents.includes(MARKER)) return config; // already patched

      const postInstallRe = /post_install do \|installer\|/;
      if (postInstallRe.test(contents)) {
        // Splice into the template's existing (single) post_install block.
        contents = contents.replace(postInstallRe, (match) => `${match}\n${SNIPPET}`);
      } else {
        // No post_install block exists yet (unexpected for an Expo/RN
        // template) — safe to add our own as a standalone block.
        contents += `\npost_install do |installer|\n${SNIPPET}\nend\n`;
      }

      fs.writeFileSync(podfilePath, contents);
      return config;
    },
  ]);
}

module.exports = withFollyCharTraitsFix;
