/* __other_flags_array_fix_v3__ */
// Auto-generated by the backend build pipeline. Do not edit by hand — it is
// re-applied idempotently on every iOS IPA build. Safe to delete: at worst
// the "no implicit conversion of String into Array" pod install crash
// (facebook/react-native#46505) returns for builds using
// use_frameworks! :linkage => :static.
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '__other_flags_array_fix_v3__';

// Read RN's actual scripts/cocoapods/utils.rb (facebook/react-native#46505):
// the crash is not in add_ndebug_flag_to_pods_in_release itself, it is one
// level deeper in the private helper it calls, add_flag_to_map_with_inheritance:
//
//   def self.add_flag_to_map_with_inheritance(map, field, flag)
//     if map[field] == nil
//       map[field] = "\$(inherited)" + flag
//     else
//       unless map[field].include?(flag)
//         map[field] = map[field] + flag   -- Array#+ String raises here
//       end
//       ...
//
// map[field].include?(flag) does NOT raise on an Array value (it just checks
// for an exact-match element, always false for a space-joined flag string),
// so an Array value sails past that guard and only dies on the next line.
// A one-time Array->String normalization taken before react_native_post_install
// runs is not reliable: RN/Xcodeproj can re-populate OTHER_CFLAGS/
// OTHER_CPLUSPLUSFLAGS as an Array again at any point between that snapshot
// and the actual crash site deep inside react_native_post_install's call
// graph, silently invalidating the earlier fix. Patching the buggy method
// itself instead of racing to pre-normalize the data is immune to that
// ordering problem — it works no matter who set the Array or when.
const SNIPPET = `
  # \${MARKER}
  # Two layers of defense, both required — confirmed by two separate CI
  # failures this fix went through:
  #
  # Layer 1 (below): pre-normalize the two data structures RN's own
  # add_ndebug_flag_to_pods_in_release (scripts/cocoapods/utils.rb) mutates.
  # NOT sufficient alone: react_native_post_install runs several of its own
  # steps first (observed in CI logs as "Setting REACT_NATIVE build settings"
  # and the Ccache-flag-removal step) that can re-populate OTHER_CFLAGS/
  # OTHER_CPLUSPLUSFLAGS as an Array again on these exact same objects AFTER
  # this snapshot runs but BEFORE add_ndebug_flag_to_pods_in_release reads
  # them later in the same call — a live CI run hit exactly this window.
  #
  # Layer 2 (further below): patch add_flag_to_map_with_inheritance itself so
  # it self-heals an Array value no matter when it was set. An earlier
  # version of this layer used a 'class ReactNativePodsUtils; class << self'
  # reopening block, which a separate live CI run proved unreliable — the
  # method_defined? guard evaluated false even though the class and method
  # demonstrably existed (confirmed by pulling the actual failed Podfile from
  # that run's CI artifact: the guard's condition never let alias_method run,
  # and the ORIGINAL, still-broken utils.rb method executed instead). This
  # version avoids that class-reopening syntax entirely — it operates via
  # explicit method calls (singleton_class.method_defined?/alias_method,
  # define_singleton_method) on the already-resolved ::ReactNativePodsUtils
  # constant, which cannot be misdirected by lexical-scope ambiguity the way
  # a bare 'class ReactNativePodsUtils' reopen apparently could be.
  other_flags_array_fix_normalize = lambda do |settings_map|
    ['OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |field|
      value = settings_map[field]
      settings_map[field] = value.join(' ') if value.is_a?(Array)
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each_value do |config_file|
      other_flags_array_fix_normalize.call(config_file.attributes)
    end
  end
  installer.target_installation_results.pod_target_installation_results.each do |_pod_name, target_installation_result|
    target_installation_result.native_target.build_configurations.each do |cfg|
      other_flags_array_fix_normalize.call(cfg.build_settings)
    end
  end

  other_flags_array_fix_utils = ::ReactNativePodsUtils
  other_flags_array_fix_singleton = other_flags_array_fix_utils.singleton_class
  if other_flags_array_fix_singleton.method_defined?(:add_flag_to_map_with_inheritance, true) &&
     !other_flags_array_fix_singleton.method_defined?(:__other_flags_array_fix_orig_add_flag_to_map_with_inheritance, true)
    other_flags_array_fix_singleton.send(
      :alias_method,
      :__other_flags_array_fix_orig_add_flag_to_map_with_inheritance,
      :add_flag_to_map_with_inheritance
    )
    other_flags_array_fix_utils.define_singleton_method(:add_flag_to_map_with_inheritance) do |map, field, flag|
      map[field] = map[field].join(' ') if map[field].is_a?(Array)
      other_flags_array_fix_utils.send(:__other_flags_array_fix_orig_add_flag_to_map_with_inheritance, map, field, flag)
    end
  end
`;

function withOtherFlagsArrayFix(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfilePath)) return config;

      let contents = fs.readFileSync(podfilePath, 'utf8');
      if (contents.includes(MARKER)) return config; // already patched

      const preInstallCallRe = /(\n\s*)react_native_post_install\(/;
      if (preInstallCallRe.test(contents)) {
        // Insert immediately before the call, at the same indentation, so it
        // runs as the last step before RN's helper reads these build settings.
        contents = contents.replace(preInstallCallRe, (match, indentedNewline) => `${indentedNewline}${SNIPPET}${indentedNewline}react_native_post_install(`);
      } else {
        // Unexpected for an Expo/RN template — nothing to anchor on, skip
        // rather than guess at a placement that could run at the wrong time.
        return config;
      }

      fs.writeFileSync(podfilePath, contents);
      return config;
    },
  ]);
}

module.exports = withOtherFlagsArrayFix;
